default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bdadb_development
  schema_search_path: public, postgis
  url: <%= ENV.fetch("DATABASE_URL", "").gsub(/postgres/, 'postgis') %>

test:
  <<: *default
  database: bdadb_test
  schema_search_path: public, postgis

production:
  <<: *default
  schema_search_path: public, postgis
  url: <%= ENV.fetch("DATABASE_URL", "").gsub(/postgres/, 'postgis') %>
